### ISSUE TITLE
Criar capa, foto de perfil e bio para a conta do PyNorte no Twitter e passar para o @luzfcb

### ISSUE THREAD

**Issue by luzfcb** [PyNorte/pynorte2023-org#11]
A conta do Twitter que será utilizada será https://twitter.com/pynorte.
O @luzfcb tem acesso para fazer essas mudanças.

Os tamanhos/limite de caracteres estão descritos em:

https://help.twitter.com/pt/managing-your-account/how-to-customize-your-profile
https://www.adobe.com/br/express/discover/sizes/twitter

**Comment by gabrovskii** [comment]
Olá @luzfcb 

Possuo acesso ao Twitter via https://tweetdeck.twitter.com/

Limitações: 

1.  Não consigo fazer alterações de foto de perfil nem de capa;

1.  Não consigo adicionar novos colaboradores (mais pessoas do time de Comunicação, por exemplo).

Sobre a questão de capa, acredito que você consiga fazer a alteração:

- Link da foto de perfil -> [Logo](https://drive.google.com/file/d/1DRmxjpoMnD4EPsWGM2ye-hiptGVYGagJ/view?usp=share_link);
-  Link da foto de capa -> [Twitter Background](https://drive.google.com/file/d/13UexJQRUahJO3jrdeQIwuRVOx1Go_ADf/view?usp=share_link)

Sobre a questão do acesso a novos colaboradores:

- No dia de hoje não é um problema, porém será uma atividade recorrente adicionar novas pessoas ao acesso da conta (a rotatividade de voluntários é relativamente alta).

**Comment by gabrovskii** [comment]
Fechando a issue e movendo as requisições para #37
