### ISSUE TITLE
ORG - Pedir acesso das redes sociais

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-org#21]

**Comment by gabrovskii** [comment]
Conversar com o Fábio e o Nilo sobre a vontade de passar para Apyb o controle de acesso as redes, para ter menos problema na organização dos próximos eventos

**Comment by luzfcb** [comment]
@gabrovskii até onde me recordo, eu já dei acesso a todos as perfis sociais a todos que precisavam ter acesso. 
Vocês ainda estão tendo problemas com acesso?
Se sim, por favor, me informe que vou procurar uma solução.

**Comment by gabrovskii** [comment]
Olá @luzfcb , temos acesso total ao Facebook, porém estamos sem acesso ao instagram e com acesso limitado ao Twitter. 

Existe a possibilidade de nos dar acessso ao Twitter  e ao instagram? nossa identidade visual está pronta está pronta e vamos começar atualizar as redes.

Twitter por exemplo temos acesso apenas a publicação de tweets, não conseguimos mudar nada da conta.

**Comment by luzfcb** [comment]
O @gabrovskii  tem acesso a tudo via https://business.facebook.com/

![image](https://user-images.githubusercontent.com/807599/232925503-1e455501-1387-4672-ab16-2e116d970878.png)

**Comment by gabrovskii** [comment]
Movendo conteúdo para a issue #37
