### ISSUE TITLE
Atividade Site

### ISSUE THREAD

**Issue by gabrovskii** [PyNorte/pynorte2023-org#27]
# Listar entregáveis, issues e datas de entrega

- [x] Comprar domínio do site
- [ ] Adicionar redes sociais na página provisória

**Comment by gabrovskii** [comment]
- [ ] Adicionar a @suamirocha no repositório do site

**Comment by eduardavr** [comment]
Qual tamanho devemos exportar o background do site? 1920x1080? E isso deve ser considerado a rolagem? Por exemplo, seria 1920 (width) e a altura "infinita" no caso a que for necessária pra gente colocar as infos?

**Comment by thaty-maru** [comment]
Seria interessante implementar no site uma página de chamada de voluntários

**Comment by Azanniel** [comment]
Realmente.

@eduardavr teria alguma ideia de design ou alguém do time de UI poderia nos passar uma ideia para esse densenvolvimento?

**Comment by gabrovskii** [comment]
Em processo de criação da V0 do site / Levantamento de requisítos;
 Acompanhar issue #26

**Comment by Azanniel** [comment]
@gabrovskii sobre a compra do domínio como será feita e quando? Tem prazo?

**Comment by luzfcb** [comment]
Nos anos anteriores estávamos usando o https://amazonia.python.org.br/

O objetivo de não usar PyNorte e sim PyCon Amazônia foi para poder em algum
momento abranger mais lugares e dar oportunidade para pessoas da região
amazônica mas fora do Brasil.

Nós (Nilo Menezes) tem autorização da Python Software Foundation para usar
o nome PyCon

Em qua., 26 de abr. de 2023 13:01, Gabriel Menezes ***@***.***>
escreveu:

**Comment by Azanniel** [comment]
Muito bom @luzfcb 

Então será que teria a possibilidade de usar tal domínio ou @gabrovskii gostaria de usar algum outro mais personalizado?

**Comment by Azanniel** [comment]
Estou levantando isso agora porque estamos tendo um impedimento quanto a parte de roteamento no site, pois uma das exigências do gh-pages é utilizar o nome do repositório pré-fixado na URL quando não temos um domínio.

A partir do momento que tivermos um domínio isso será solucionado, eu acredito ✨

**Comment by luzfcb** [comment]
@Azanniel provavelmente pro site funcionar no amazonia.python.org.br sem precisar mudar entrada no DNS do python.org.br, seria só renomear o repositório  https://github.com/PyNorte/pynorte2023 para https://github.com/PyNorte/pynorte, mudar renomear a branch main para outra coisa, e criar uma nova branch main que conterá o código HTML do site. 

```
$ dig amazonia.python.org.br +nostats +nocomments +nocmd

;amazonia.python.org.br.                IN      A
amazonia.python.org.br. 300     IN      CNAME   pynorte.github.io.
pynorte.github.io.      1667    IN      A       185.199.111.153
pynorte.github.io.      1667    IN      A       185.199.109.153
pynorte.github.io.      1667    IN      A       185.199.108.153
pynorte.github.io.      1667    IN      A       185.199.110.153
```

**Comment by jailsonpj** [comment]
Achei massa demais mas acredito que os BK (@thaty-maru @gabrovskii ) tem algum ponto em relação pela escolha de ser Python Norte, houve uma conversa com a organização desse ano relacionado a isso. O bom seria verificar antes com eles e ver o que eles decidirem pq toda a identidade visual do evento está concetado com esse nome.

**Comment by luzfcb** [comment]
@thaty-maru qual será o domínio escolhido? Acredito que vocês podem comprar o dominio pela conta do Pynorte no Cloudflare diretamente pelo registrador de domínio do Cloudflare, que tem preços beeem competitivos e ainda facilita a vida em outros problemas.

@gabrovskii te mandei o convite para entrar na organização Pynorte no Cloudflare.

Se houver problema com dinheiro, eu posso comprar o dominio escolhido e eu mesmo pago.

![image](https://user-images.githubusercontent.com/807599/234665996-166398dd-e0d9-40bc-bb76-6dec81057c26.png)

**Comment by thaty-maru** [comment]
> @thaty-maru qual será o domínio escolhido? Acredito que vocês podem comprar o dominio pela conta do Pynorte no Cloudflare diretamente pelo registrador de domínio do Cloudflare, que tem preços beeem competitivos e ainda facilita a vida em outros problemas.
> 
> @gabrovskii te mandei o convite para entrar na organização Pynorte no Cloudflare.
> 
> Caso nesse momento houver problema com dinheiro, eu posso comprar o domínio escolhido e eu mesmo pago e a organização do evento não precisa me ressarcir em nada.
> 
> ![image](https://user-images.githubusercontent.com/807599/234667554-a614ed44-ae51-4965-a4a4-862a0a231d4f.png)

Vamos discutir sobre o domínio hoje em reunião.
Muito obrigada pela contribuição.

**Comment by rougeth** [comment]
Pessoas, domínio comprado pela APyB e subdomínio configurado para apontar para `pynorte.github.io`. Quem tiver permissão no repositório, precisa configurar a seção Pages para apontar para o novo endereço: https://github.com/pynorte/pynorte2023-site/settings/pages.

```
❯ dig +short 2023.pythonnorte.org
pynorte.github.io.
185.199.109.153
185.199.108.153
185.199.110.153
185.199.111.153
```

**Comment by Azanniel** [comment]
Com a adição do domínio, essa issue ainda ficará aberta? @gabrovskii

**Comment by gabrovskii** [comment]
@Azanniel vou renomear essa isue para "Compra do domínio do site" e fechar.

Vou abrir uma outra para acompanhar outras tarefas do site.
