### ISSUE TITLE
Plano de patrocínio

### ISSUE THREAD

**Issue by gabrovskii** [PyNorte/pynorte2023-org#28]
### Criar documento do plano de patrocínio

- [x] Plano de patrocínio;
- [x] Criar cotas e valores;
- [x] Validar valores das cotas

Links úteis: 

- [Cotas Python Norte 2023](https://docs.google.com/spreadsheets/d/1cBZTIwkp7qTpX1CVFlQcHegi3A8LJ06EwK1OwwBgnSw/edit?usp=sharing)

-  [Itens Para orçar Python Norte 2023](https://docs.google.com/document/d/1wgFuhskv7rYoTSYPguBHfvCPiP7wl_QxB3WufwNaTJ8/edit?usp=sharing)

- [Plano de patrocínio Python Brasil 2022](https://drive.google.com/file/d/16fP5BH_GF1hgb_ttfHQgEI88p7tOg1uB/view)

**Comment by gabrovskii** [comment]
Quais os requisitos que precisamos analisar para definir os valores das cotas?

**Comment by thaty-maru** [comment]
Empresas de Manaus tem o costume de querer estes itens nos eventos:
- Estandes
- Palestras
- Visibilidade
- Sorteios

Podemos incluir cota de apoio em troca de divulgação

**Comment by gabrovskii** [comment]
Quais itens necessários para orçar?

**Comment by thaty-maru** [comment]
Podemos utilizar as cotas da Python Nordeste, visto que o padrão do evento é quase o mesmo (alteramos apenas pro nosso evento)

**Comment by gabrovskii** [comment]
Temos nossos valores!  -> [Plano de patrocínio Python Norte 2023- Cotas](https://docs.google.com/spreadsheets/d/1cBZTIwkp7qTpX1CVFlQcHegi3A8LJ06EwK1OwwBgnSw/edit#gid=0)

**Comment by joaolucaschagas** [comment]
Valores do Plano de Parocinio Atualizado, conforme último alinhamento, foram retirada as cotas da prata.
Atualização os valores das cotas: Ouro(Antes 2 - Agora 3); Diamante (Antes 1 - Agora 2).
Revogado o direito do estande, da cota prata.
@gabrovskii @thaty-maru

**Comment by joaolucaschagas** [comment]
Aguardando somente o feedback de vcs, para fechar a Issue ^^

**Comment by thaty-maru** [comment]
> Aguardando somente o feedback de vcs, para fechar a Issue ^^

por mim ta perfeito! Só começar os contatos
@gabrovskii @jailsonpj o que vcs acham?

**Comment by jailsonpj** [comment]
Tá ótimo!

**Comment by gabrovskii** [comment]
@thaty-maru Adicionar os 10% da Apyb

**Comment by gabrovskii** [comment]
Valores ajustados

**Comment by gabrovskii** [comment]
Adicionar os valores do doc de patrocínio @eduarda
