### ISSUE TITLE
Código de conduta

### ISSUE THREAD

**Issue by gabrovskii** [PyNorte/pynorte2023-org#29]
### Criar Código de conduta

- [ ]  Código de conduta

Links úteis: 
- [Código de conduta Python Brasil 2022](https://2022.pythonbrasil.org.br/cdc)

**Comment by gabrovskii** [comment]
[Código de conduta Python Norte 2023](https://docs.google.com/document/d/1DaCl2dWJI_LV_AeLb-9E1LkKp7TNePsMm9XvZo-sPD4/edit?usp=sharing)

Dúvida: podemos utilizar o mesmo código de conduta da python Brasil? 
Existe um padrão para ser utilizado disponibilizado pela Apyb?

**Comment by gabrovskii** [comment]
ATT: Verificar a possibilidade de adicionar membros da Apyb no repositório.

**Comment by thaty-maru** [comment]
@gabrovskii vai ser utilizado o código de conduta padrão dos evento da Apyb?

**Comment by gabrovskii** [comment]
Concluído.
