### ISSUE TITLE
Texto de contato

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-org#33]
## Texto para chamada de patrocínio

- [Texto para chamada de patrocínio](https://docs.google.com/document/d/1ButrupYu2wgeDiTe-dlGLhrQ5g9e9la0VQEkMFkZmrE/edit?usp=sharing)

**Comment by thaty-maru** [comment]
@gabrovskii pode dar um proofread depois pfvr?

**Comment by gabrovskii** [comment]
@thaty-maru o que é proofread kkk?

**Comment by gabrovskii** [comment]
@thaty-maru Fiz pequenas alterações, você está de acordo?


Olá <Nome destinatário>. Bom dia!

Meu nome é < Nome remetente > e faço parte da organização da Python Norte 2023, evento voltado para a linguagem de programação Python que acontecerá em Manaus-AM em outubro de 2023.

A Python Norte 2023 tem como objetivo difundir a linguagem Python em universidades, empresas, instituições da sociedade civil e indivíduos que buscam novos conhecimentos, além de promover uma cultura aberta e colaborativa de desenvolvimento de software na Região Norte.

O lema do nosso evento é Pessoas > Tecnologia, que signifca que apesar do evento ser voltado para a tecnologia, o nosso objetivo principal são as pessoas que estão participando direta ou indiretamente. Estamos com a espectativa de receber 150 pessoas, entre estudantes, empresas da área de tecnologia, indústria e inovação, entre outras áreas.

Estamos em busca de empresas que possam apoiar a PyN 2023, e a/o < Nome da empresa > foi uma das empresas visadas pela organização pois < Motivos para escolhermos a empresa >.

Estamos enviando a apresentação do evento com detalhes e se houver interesse temos um Plano de Patrocínio que gostaríamos de apresentar para vocês. Podemos agendar uma reunião para discutir uma possível colaboração?

Ficamos no aguardo do seu retorno. Desde já, obrigada!
<Rodapé da Organização Python Norte>

**Comment by gabrovskii** [comment]
@thaty-maru Podemos fechar essa issue? podemos levar o texto para um doc do drive.

**Comment by joaolucaschagas** [comment]
@thaty-maru @gabrovskii guys, fiz uma alteração no texto:
Olá <Nome destinatário>. Bom dia!

Meu nome é < Nome remetente > e faço parte da organização da Python Norte 2023, evento voltado para a linguagem de programação Python que acontecerá em Manaus-AM em outubro de 2023.

A Python Norte 2023 tem como objetivo difundir a linguagem Python em universidades, empresas, instituições da sociedade civil e indivíduos que buscam novos conhecimentos e trocas de experiências, além de promover uma cultura aberta e colaborativa de desenvolvimento de software na Região Norte.

O lema do nosso evento é Pessoas > Tecnologia, que significa que apesar do evento ser voltado para a tecnologia, o nosso objetivo principal são as pessoas que estão participando direta ou indiretamente. Estamos com a expectativa de receber um público variável, entre estudantes, empresas da área de tecnologia, indústria e inovação, entre outras áreas.

Estamos em busca de empresas que possam apoiar a PyN 2023, e a/o < Nome da empresa > foi uma das empresas visadas pela organização pois < Motivos para escolhermos a empresa >.

Estamos enviando a apresentação do evento com detalhes e se houver interesse temos um Plano de Patrocínio que gostaríamos de apresentar para vocês. Podemos agendar uma reunião para discutir uma possível colaboração, e tirar algumas dúvidas sobre a PyN 2023?

Ficamos no aguardo do seu retorno. Desde já, obrigada!
<Rodapé da Organização Python Norte>

**Comment by joaolucaschagas** [comment]
@gabrovskii @thaty-maru Estão de acordo?

**Comment by thaty-maru** [comment]
> @gabrovskii @thaty-maru Estão de acordo?

Está ótimo!

**Comment by joaolucaschagas** [comment]
@gabrovskii @thaty-maru tomei a liberdade, de passar pro espanhol e para o inglês.
A noite mando para vcs!

**Comment by joaolucaschagas** [comment]
Update:
Olá <Nome destinatário>. Bom dia!

Meu nome é < Nome remetente > e faço parte da organização da Python Norte 2023, evento voltado para a linguagem de programação Python que acontecerá em Manaus-AM em outubro de 2023.

A Python Norte 2023 tem como objetivo difundir a linguagem Python em universidades, empresas, instituições da sociedade civil e indivíduos que buscam novos conhecimentos e trocas de experiências, além de promover uma cultura aberta e colaborativa de desenvolvimento de software na Região Norte.

O lema do nosso evento é Pessoas > Tecnologia, que significa que apesar do evento ser voltado para a tecnologia, o nosso objetivo principal são as pessoas que estão participando direta ou indiretamente. Estamos com a expectativa de receber um público variável, entre estudantes, empresas da área de tecnologia, indústria e inovação, entre outras áreas.

Estamos em busca de empresas acreditem no projeto, é uma oportunidade de associar a sua marca a uma iniciativa aberta e colaborativa com uma visibilidade nacional. A a/o <empresa> foi visada pela organização pois ,a sua importância e a sua cultura, vão de encontro com o que nos, da PyN2023, acreditamos!

Segue em anexo a apresentação do evento com detalhes, e se houver interesse temos um Plano de Patrocínio que gostaríamos de apresentar para vocês!
 Podemos agendar uma reunião para discutir uma possível colaboração, e tirar algumas dúvidas sobre a PyN 2023?

Ficamos no aguardo do seu retorno. Desde já, obrigada!
<Rodapé da Organização Python Norte>

**Comment by joaolucaschagas** [comment]
@gabrovskii @thaty-maru Fico no aguardo do feedback de vcs ^^

**Comment by thaty-maru** [comment]
Por mim tá ótimo!

**Comment by gabrovskii** [comment]
** Estamos em busca de empresas que acreditem no projeto, é uma oportunidade de associar a sua marca a uma iniciativa aberta e colaborativa. A <empresa> foi visada pela organização pois  sua cultura vão de encontro com o que nós, da PyN2023, acreditamos!

**Comment by thaty-maru** [comment]
Update:
Olá <Nome destinatário>.

Meu nome é < Nome remetente > e faço parte da organização da Python Norte 2023, evento voltado para a linguagem de programação Python que acontecerá em Manaus-AM em setembro de 2023.

A Python Norte 2023 tem como objetivo difundir a linguagem Python em universidades, empresas, instituições da sociedade civil e indivíduos que buscam novos conhecimentos e trocas de experiências, além de promover uma cultura aberta e colaborativa de desenvolvimento de software na Região Norte.

O lema do nosso evento é Pessoas > Tecnologia, que significa que apesar do evento ser voltado para a tecnologia, o nosso objetivo principal são as pessoas que estão participando direta ou indiretamente. Estamos com a expectativa de receber um público variável, entre estudantes, empresas da área de tecnologia, indústria e inovação, entre outras áreas.

Estamos em busca de empresas que acreditem no projeto, é uma oportunidade de associar a sua marca a uma iniciativa aberta e colaborativa com uma visibilidade nacional. A/O < empresa contatada > foi visada pela organização pois a sua importância e a sua cultura vão de encontro com o que nós, da PyN23, acreditamos!

Segue em anexo o plano de patrocínio do evento com detalhes, e se houver interesse podemos agendar uma reunião para discutir uma possível colaboração, e tirar algumas dúvidas sobre a PyN23?

Ficamos no aguardo do seu retorno. Desde já agradecemos!
<Rodapé da Organização Python Norte>

**Comment by thaty-maru** [comment]
Texto para o Linkedin:

Olá. Meu nome é <remetente> e faço parte da organização da Python Norte 2023, evento voltado para a linguagem de programação Python que acontecerá em Manaus-AM nos dias 29 e 30 de setembro de 2023. Podemos agendar uma reunião para discutir uma possível colaboração, e tirar alguma dúvida sobre a PyN23?
