### ISSUE TITLE
Adição do webhook do github no discord para monitorar atividades

### ISSUE THREAD

**Issue by Azanniel** [PyNorte/pynorte2023-org#36]
E aí, pessoal?

Minha sugestão é adicionar o webhook do [github do site](https://github.com/PyNorte/pynorte2023-site) no discord para monitorar as atividades (issues) e pull requests.

Além disso, irá nos ajudar caso hajam novas PR's que necessitem de revisão notificando no discord.

[Guia de como adicionar](https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22)

**Comment by gabrovskii** [comment]
Testing

**Comment by Azanniel** [comment]
Acredito que ainda não tenha funcionado, pois fiz um comentário na issue https://github.com/PyNorte/pynorte2023-site/issues/6

E pela imagem não foi notificado pelo webhook

![image](https://user-images.githubusercontent.com/71537090/233413364-c802cacb-2dda-448f-97b3-00ad5fb43fb2.png)

**Comment by Azanniel** [comment]
Parece que agora funcionou @gabrovskii
