### ISSUE TITLE
Patrocínio Vinta

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-org#50]

**Comment by joaolucaschagas** [comment]
Plano de patrocinio enviado para a empresa

**Comment by thaty-maru** [comment]
## No dia 25/05/2023:
 > Legal, João Lucas! Valeu teu retorno.
Temos interesse nas Cotas Bronze. Quais os próximos passos pra fecharmos a parceria? 
Do lado de cá, preciso confirmar que vocês emitem NF.

> Olá, ########.
Fazemos emissão de Nota Fiscal, sem problemas.
Vamos elaborar o contrato de patrocínio e enviar para análise. Estando tudo certo, haverá a assinatura de ambas as partes.
Por enquanto, pedimos estes dados para elaborarmos a minuta do contrato:
Desde já agradecemos o interesse em contribuir com nosso evento 🐍❤

> Foram enviados os dados

## No dia 01/06/2023:

> Foi enviado o contrato para análise.

## No dia 09/06/2023:

> Oi, João Lucas, como vai? 
Me chamo ########, trabalho junto com o ####### na Vinta. A partir de agora vamos nos comunicar para dar seguimento aos detalhes do patrocínio. :)
Revisamos o contrato e podemos seguir com ele. Você vai enviar o modelo em PDF para assinatura? 
Também seria possível vocês passarem a agenda do evento, keynotes e expectativa de público?
Adicionalmente, sobre o que temos direito na posição de patrocinadores (anexo) iremos alinhar mais pra frente os detalhes, não é? Antes de haver divulgação de logo e comunicação envolvendo a Vinta, vamos fazer um crosscheck, certo? 
Abs,

> Sim, vamos enviar o contrato para assinatura digital, já estamos providenciando.
Estamos montando também nosso cronograma com os keynotes e palestras, assim que estiver pronto posso te mandar.
Sobre a data do evento, definimos para a segunda quinzena de outubro, estamos avaliando todas as possibilidades que melhor atenda o público, por isso não definimos ainda😔.
Nós adoraríamos marcar uma reunião para sanar todas as dúvidas restantes.
Fico no aguardo do seu retorno.

## No dia 14/06/2023:
> Oi João Lucas!
Não precisamos marcar uma reunião. Vou deixar o que eu preciso saber aqui reunido aqui nesse e-mail pra ficar mais fácil e você me retorna assim que souber, por favor:
- Agenda do evento, keynotes e expectativa de público;
- Data do evento, para informarmos internamente;
- Antes de divulgar qualquer comunicação com a logo da Vinta, me enviar pra validarmos antes, ok? 
- Adicionalmente, também preciso saber se caso o evento seja cancelado, receberemos o valor investido de volta? Como funciona nesse caso?
Fico no aguardo do contrato para assinatura digital. ;)

## No dia 20/06/2023, respondemos:
> Desculpe a demora, estávamos com alguns problemas internos.
Sobre as perguntas:
- A programação do evento e os keynotes ainda estão em processo de seleção. Os keynotes são escolhidos pela comunidade e pela organização também, e as palestras e tutorias são ministrados pela própria comunidade, então ambos passam por um período de submissão e avaliação. Assim que tivermos atualização, podemos mandar para vocês. Sobre a expectativa de público, estamos pretendendo receber aproximadamente 150 pessoas.
- A data do evento foi alterada por conta de outro evento que foi anunciado. Será agora na segunda quinzena de setembro de 2023 (acreditamos que nos dias 29 e 30 de Setembro).
- Antes de qualquer divulgação nós fazemos a validação das artes com os patrocinadores para que não haja nenhum problema com relação a identidade visual, podem ficar tranquilos.
- Com relação a um possível cancelamento do evento, nós estamos trabalhando duro para que essa situação não ocorra, mas podemos acrescentar esta cláusula ao contrato para que vocês fiquem tranquilos com relação a isso.
Estamos providenciando uma plataforma de assinatura online para ficar mais confortável para todos. Caso não consigamos, envio o documento em PDF para assinatura, tá bom?
Mais uma vez muito obrigado por acreditar no nosso evento

## No dia 21/06/2023:
> Certo, assim que tiver atualização sobre a programação do evento, me informa, por favor. 
E sim, adiciona a cláusula ao contrato em caso de cancelamento do evento e retorno do valor investido, por favor. Fica mais seguro pra gente. Aí você adiciona a cláusula e manda o contrato pra gente revisar e assinar, tá bom? 
Fico no aguardo, abraços.

> Fiz as alterações no contrato, e segue anexo para validação.
Fico no aguardo da validação para seguirmos com os próximos passos.

> Validado. Podemos seguir assim! Você que fica responsável de enviar para assinatura? 

> Sim, nós vamos ficar responsáveis pela assinatura. Assim que estiver tudo ok enviamos o link para assinatura. Precisamos de dois nomes e CPFs para acrescentar ao documento para assinatura.

## No dia 22/06/2023:

> Forma enviados os dados das testemunhas e o responsável da empresa.

> Foi enviado o e-mail do Docusign para assinatura do contrato. Pode confirmar o recebimento por gentileza.
Obrigada mais uma vez por acreditar no nosso projeto.

## No dia 05/07/2023:

>  Esqueci de responder mas você deve ter visto que assinamos o contrato. Vamos efetuar o pagamento amanhã. Você poderia me informar uma chave PIX?

> As próximas negociações foram feitas pelo Whatsapp, mas no fim deu tudo certo e foi realizado o depósito na conta a Apyb.

**Comment by joaolucaschagas** [comment]
Thaty (vinta) entrou em contato para sugerir sorteio de brindes, que a mesma providenciara.
A vinta não teve interesse em ter algo relacionado a marca na sacola de brindes.

Os brindes para sorteio com, com os equipamentos da vinta, serão encaminhados para o endereço fornecido
