### ISSUE TITLE
Orçamento ICBEU

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-org#55]

**Comment by gabrovskii** [comment]
# ICBEU

Visita ao local no dia 09/10/23

Espaços:
1-Teatro com capacidade para 400 pessoas;
2-galeria rotativa com capacidade para 200 pessoas;
3- 4 salas para utilizar de formas diversas (robótica, culinária(sala mix), informática, biblioteca) capacidade entre 15 e 30 pessoas. 
4- Hall interno que pode ser utilizado para montar os estandes. 
5-talvez salas de aulas(dependendo do dia e da disponibilidade da sala)

Observações:
-Precisamos ter nossa equipe de limpeza;
-Levar acessórios de usos diversos como pilhas para os controles, passadores de slides...
-possuem um palco pequeno 2x2
-Espaço da galeria e teatro possuem sistema de som e de projeção inclusos 
-para utilizar a galeria, pelo que estendi precisaríamos locar mais cadeiras pois possuem um número limitado no local. 


Limitações:
- Sábado por ser um dia muito movimentado, é quase impossível se locar o espaço;

Minhas considerações:
Gabriel Menezes: 
- O teatro é grande demais para o que pretendemos fazer 
- Uma boa opção A, mas me parece caro pela excelente estrutura que o ICBEU possui; valores não puderam ser discutidos pois o teatro está em reforma e só poderá ser visto a partir de junho. 

Já idealizando o evento no local, os keynotes iriam ocorrer na galeria, as palestras nas salas de apoio e os estandes nono hall principal (precisa pegar elevador, acredito ser no segundo andar) 

Uns 2 minutos andando entre a galeria e o hall/ sala 

Nota 8 de 10.

**Comment by joaolucaschagas** [comment]
Aguardando retorno do orçamento

**Comment by gabrovskii** [comment]
Fechando pois seguiremos com a uninorte.
